kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    repo: unilang
    tags: latest
    dry_run: true
  commands:
  - docker build -t unilang .
  - docker run unilang ./ci_scripts/drone
