kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    repo: unilang
    tags: latest
    dry_run: true
  commands:
  - echo 'docker build -t unilang .'
  - echo 'docker run unilang ./ci_scripts/drone'
