kind: pipeline
name: default

steps:
- name: build
  image: docker
  commands:
    - echo 'docker build -t unilang .'
    - echo 'docker run unilang ./ci_scripts/drone'
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
