pipeline:
  ping:
    image: docker
    environment:
      - DOCKER_HOST=unix:///drone/docker.sock
    commands:
      - sleep 10 # give docker enough time to initialize
      - docker ps -a

services:
  docker:
    image: docker:dind
    privileged: true
    command: [ '-H', 'unix:///drone/docker.sock' ]
