kind: pipeline
name: default

steps:
- name: build
  image: docker
  environment:
    - DOCKER_HOST=unix:///drone/docker.sock
  commands:
    - echo docker build -t unilang .
    - echo docker run unilang ./ci_scripts/drone
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

services:
  docker:
    image: docker:dind
    privileged: true
    command: [ '-H', 'unix:///drone/docker.sock' ]
