build:
  nodes:
    coverage:
      environment:
        docker: true
      tests:
        before:
          - command: docker build -t unilang -f Dockerfile .
          - command: docker run unilang ./ci_scripts/scrutinizer
            idle_timeout: 1200
