# Site settings
title: Linguistics
tag_text: Linguistics
description: Linguistics
tagline: "A Monograph on Applying Linguistics to Software Engineering"
url: "https://luxe.github.io/linguistics/"
host: 127.0.0.1
port: 4000
baseurl: "/linguistics"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown
exclude: [".htaccess"]