version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y m4
      - run: apt-get install -y libgmp3-dev
      - run: apt-get install -y xorg
      - run: apt-get install -y libsdl2-dev
      - run: ./ci_scripts/circle
