version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    steps:
      - checkout
      - run: apt-get install -y m4
      - run: apt-get install -y libgmp3-dev
      - run: ./ci_build
