title:            Hickey Rates Things
description:      I rate things bi-monthly
logo:             site-logo.png
disqus_shortname: 
search:           true
# Change url to your domain. Leave localhost server or blank when working locally.
# You don't need to specify the protocol if you want it available on http and https. Example: //localhost:4000
url:              http://luxe.github.io/hickey-rates

# Owner/author information
owner:
  name:           Trevor Hickey
  avatar:         bio-photo.jpg
  email:          TrevorJamesHickey@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: TREV0RR
  facebook:
  github: luxe
  stackexchange: http://stackoverflow.com/users/908939/trevor-hickey
  linkedin: pub/trevor-hickey/73/2a0/6b0
  instagram: the_hikikomori_and_his_hound
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Archives
    url: /archives/
  - title: Scores
    url: /scores/
  - title: About
    url: /about/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess", "items/"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "README.md", "LICENSE", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
